server:
  port: 8005

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:

# 在dev环境开启mybatis的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置域名，在java代码中获取，这里是资源配置
website:
  domain-name: admin.sn.com
