############################################################
#
# 用户微服务
# web访问端口号  约定：8003
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1   # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: prod
  application:
    name: service-user
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  datasource:
#    url: jdbc:mysql://localhost:3306/live?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#    hikari:
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver