server:
  port: 8003

# redis配置
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

# 设置域名，在java代码中获取
website:
  domain-name: www.taotao.com

# dev环境开启mybatis日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
